"""Configuration module exports."""

from nora.config.constants import (
    NORA_DIR_NAME,
    SETTINGS_FILENAME,
    MODES_DIR_NAME,
    THREADS_DIR_NAME,
    PLANS_DIR_NAME,
    PLUGINS_DIR_NAME,
    DEFAULT_MODEL_ID,
    AVAILABLE_MODELS,
    MODE_COLORS,
    MODE_CYCLE,
    COMMANDS,
    MAX_AUTOCOMPLETE_RESULTS,
    MAX_FILE_SIZE,
    PLUGIN_MATCH_THRESHOLD,
)
from nora.config.prompts import (
    BASE_PROMPT,
    DEFAULT_VIBE_PROMPT,
    DEFAULT_PLAN_PROMPT,
    DEFAULT_EDIT_PROMPT,
    SUBAGENT_PROMPT,
    DEFAULT_PROMPTS,
    get_mode_prompt,
)

__all__ = [
    # Constants
    "NORA_DIR_NAME",
    "SETTINGS_FILENAME",
    "MODES_DIR_NAME",
    "THREADS_DIR_NAME",
    "PLANS_DIR_NAME",
    "PLUGINS_DIR_NAME",
    "DEFAULT_MODEL_ID",
    "AVAILABLE_MODELS",
    "MODE_COLORS",
    "MODE_CYCLE",
    "COMMANDS",
    "MAX_AUTOCOMPLETE_RESULTS",
    "MAX_FILE_SIZE",
    "PLUGIN_MATCH_THRESHOLD",
    # Prompts
    "BASE_PROMPT",
    "DEFAULT_VIBE_PROMPT",
    "DEFAULT_PLAN_PROMPT",
    "DEFAULT_EDIT_PROMPT",
    "SUBAGENT_PROMPT",
    "DEFAULT_PROMPTS",
    "get_mode_prompt",
]
